import type { DeliveryItem } from "../agentTypes";

export const DELIVERY_STATUS = {
  ASSIGNED: "ASSIGNED",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
};

export const deliveryMock = {
  shipmentId: 1,
  trackingId: "TRK-001-XYZ",
  currentStatus: DELIVERY_STATUS.IN_TRANSIT,
  timeline: [
    {
      key: DELIVERY_STATUS.ASSIGNED,
      label: "Assigned",
      description: "Delivery assigned to agent",
    },
    {
      key: DELIVERY_STATUS.PICKED_UP,
      label: "Picked Up",
      description: "Package collected from sender",
    },
    {
      key: DELIVERY_STATUS.IN_TRANSIT,
      label: "In Transit",
      description: "Heading to delivery location",
    },
    {
      key: DELIVERY_STATUS.OUT_FOR_DELIVERY,
      label: "Out for Delivery",
      description: "Last mile delivery started",
    },
    {
      key: DELIVERY_STATUS.DELIVERED,
      label: "Delivered",
      description: "Package delivered successfully",
    },
  ],
};

export const mockDeliveries: DeliveryItem[] = [
  {
    shipmentId: 1,
    trackingId: "TRK-1778944014299-3U9CH4",
    customerId: 3,
    itemName: "Laptop",
    quantity: 3,
    packageWeight: 2.5,
    isFragile: true,
    senderName: "Abi",
    senderPhone: "+91 87654 32109",
    description: "Handle with care. Call before arriving.",
    pickupAddress: "No.12, MG Road",
    pickupCity: "Bangalore",
    pickupPincode: "560001",
    deliveryAddress: "No.45, Indiranagar",
    deliveryCity: "Bangalore",
    deliveryPincode: "560038",
    receiverName: "Jane Smith",
    receiverPhone: "+91 98765 12345",
    shipmentPriority: "SAME_DAY",
    shipmentStatus: "OUT_FOR_DELIVERY",
    amount: 620,
    paymentStatus: "PAID",
    assignedSlotStart: "10:00 AM",
    assignedSlotEnd: "11:00 AM",
    assignedDate: "2026-05-18",
    createdAt: "2026-05-18T04:00:00.000Z",
    updatedAt: "2026-05-18T05:10:00.000Z",
  },

  {
    shipmentId: 2,
    trackingId: "TRK-1778946022243-2M2UAI",
    customerId: 5,
    itemName: "Clothes",
    quantity: 2,
    packageWeight: 1.2,
    isFragile: false,
    senderName: "Meera Singh",
    senderPhone: "+91 90000 11111",
    description: "Leave at security if unavailable.",
    pickupAddress: "Koramangala",
    pickupCity: "Bangalore",
    pickupPincode: "560095",
    deliveryAddress: "Whitefield",
    deliveryCity: "Bangalore",
    deliveryPincode: "560066",
    receiverName: "Rahul",
    receiverPhone: "+91 81111 22222",
    shipmentPriority: "EXPRESS",
    shipmentStatus: "IN_TRANSIT",
    amount: 340,
    paymentStatus: "PAID",
    assignedSlotStart: "02:00 PM",
    assignedSlotEnd: "03:00 PM",
    assignedDate: "2026-05-17",
    createdAt: "2026-05-17T04:00:00.000Z",
    updatedAt: "2026-05-17T05:10:00.000Z",
  },
  {
    shipmentId: 3,
    trackingId: "TRK-1778946022243-2M2UAI",
    customerId: 5,
    itemName: "Clothes",
    quantity: 2,
    packageWeight: 1.2,
    isFragile: false,
    senderName: "Meera Singh",
    senderPhone: "+91 90000 11111",
    description: "Leave at security if unavailable.",
    pickupAddress: "Koramangala",
    pickupCity: "Bangalore",
    pickupPincode: "560095",
    deliveryAddress: "Whitefield",
    deliveryCity: "Bangalore",
    deliveryPincode: "560066",
    receiverName: "Rahul",
    receiverPhone: "+91 81111 22222",
    shipmentPriority: "EXPRESS",
    shipmentStatus: "IN_TRANSIT",
    amount: 340,
    paymentStatus: "PAID",
    assignedSlotStart: "02:00 PM",
    assignedSlotEnd: "03:00 PM",
    assignedDate: "2026-05-17",
    createdAt: "2026-05-17T04:00:00.000Z",
    updatedAt: "2026-05-17T05:10:00.000Z",
  },
];

export const formatDate = (iso: string) => {
  if (!iso) return "—";

  return new Date(iso).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};